{{- $labels := include "nodejs.labels" . -}}
{{- $selectorLabels := include "nodejs.selectorLabels" . -}}

{{- range .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "nodejs.fullname" $ }}-{{ .name }}
  labels:
  {{- $labels | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "nodejs.fullname" $ }}-{{ .name }}
      labels:
    {{- $labels | nindent 8 }}
    spec:
      serviceAccountName: {{ template "nodejs.serviceAccountName" $ }}
      restartPolicy: Never
      containers:
        - name: {{ $.Chart.Name }}-{{ .name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with .command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.secretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          {{- end }}
          {{- if and (.Values.secretMountPath) (.Values.secretFileName) }}
          volumeMounts:
            - name: env
              mountPath: {{ .Values.secretMountPath }}
              readOnly: true
              subPath: .env
      {{- end }}
      {{- if and (.Values.secretMountPath) (.Values.secretFileName) }}
      volumes:
        - name: env
          secret:
            secretName: {{ .Values.secretFileName }}
  {{- end }}
---
{{- end }}