{{- $labels := include "nodejs.labels" . -}}
{{- $selectorLabels := include "nodejs.selectorLabels" . -}}

{{- range .Values.workers }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodejs.fullname" $ }}-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
    worker: {{ .name }}
spec:
{{- if not $.Values.autoscaling.enabled }}
  replicas: {{ .replicaCount | default 1 }}
{{- end }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      worker: {{ .name }}
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        worker: {{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "nodejs.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}-{{ .name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with .command }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $.Values.secretName }}
          envFrom:
            - secretRef:
                name: {{ $.Values.secretName }}
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---   
{{- end }}